create table OST
(
	IdOst		int primary key identity,
	Ost			nvarchar(20),
	IdCliente	int references Cliente(IdCliente),
	RUC			nvarchar(20),
	Contacto	nvarchar(150),
	Correo		nvarchar(150),
	Telefono	nvarchar(20),
	Deja		nvarchar(150),
	Dni			nvarchar(20),
	IdEquipo	int references Equipo(IdEquipo),
	Marca		nvarchar(150),
	Modelo		nvarchar(150),
	Serie		nvarchar(150),
	FechaVenta	date,
	Diagnostico nvarchar(1000),
	Mantenimiento	bit,
	Revision		bit,
	Reparacion		bit,
	Tiempo	int,
	Moneda	int references Monedas(IdMoneda),
	Costo	float,
	EstadoOst	int references EstadoOst(IdEstadoOst),
	Informe		nvarchar(1000),
	Acesorios	nvarchar(1000),
	FechaDiagnostico date,
	FechaOst	date
)